/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jni_HelloWorld */

#ifndef _Included_com_example_jni_HelloWorld
#define _Included_com_example_jni_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jni_HelloWorld
 * Method:    init
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_jni_HelloWorld_init
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_jni_HelloWorld
 * Method:    printf
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_jni_HelloWorld_printf
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
